In [1]:
import numpy as np
import pandas as pd

In [2]:
long_series = pd.Series(np.random.randn(1000))
print long_series.head()
print long_series.tail()

0   -0.582108
1   -0.863240
2   -3.626913
3    1.958452
4   -0.481986
dtype: float64
995   -1.027824
996    0.963711
997    0.792358
998   -0.218449
999   -0.002880
dtype: float64


In [3]:
index = pd.date_range('2000-01-01', periods=8)
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=['A', 'B', 'C'])
df.columns = [x.lower() for x in df.columns]
print df

                   a         b         c
2000-01-01  0.328590  1.439517 -0.212495
2000-01-02 -0.140952  0.201381 -1.185168
2000-01-03 -1.089701  0.800202 -0.113148
2000-01-04 -0.182381 -0.914860 -0.203346
2000-01-05  0.342428  0.430906  2.343374
2000-01-06  0.398791  0.595992  0.824954
2000-01-07  0.011249 -0.543641  1.142912
2000-01-08  0.690409  0.290071 -0.380978


In [4]:
print df.values, type(df.values)

[[ 0.32858992  1.43951708 -0.21249524]
 [-0.14095202  0.20138058 -1.18516833]
 [-1.08970145  0.80020209 -0.11314812]
 [-0.18238098 -0.91485969 -0.20334608]
 [ 0.34242771  0.43090647  2.34337407]
 [ 0.39879056  0.59599157  0.82495396]
 [ 0.0112493  -0.54364052  1.14291216]
 [ 0.69040884  0.29007145 -0.38097825]] <type 'numpy.ndarray'>


In [5]:
df = pd.DataFrame({'one' : pd.Series(np.random.randn(3), index=['a', 'b', 'c']),
                    'two' : pd.Series(np.random.randn(4), index=['a', 'b', 'c', 'd']),
                    'three' : pd.Series(np.random.randn(3), index=['b', 'c', 'd'])})
print df

        one     three       two
a  0.577716       NaN -0.103012
b -0.958164 -1.484507 -0.382895
c -0.358257 -0.105039  0.682108
d       NaN -0.168444 -0.311164


In [6]:
row = df.ix[1]
column = df['two']
print row
print column

one     -0.958164
three   -1.484507
two     -0.382895
Name: b, dtype: float64
a   -0.103012
b   -0.382895
c    0.682108
d   -0.311164
Name: two, dtype: float64


In [7]:
df.sub(row, axis='columns')

one     three       two
a  1.535880       NaN  0.279883
b  0.000000  0.000000  0.000000
c  0.599907  1.379468  1.065003
d       NaN  1.316063  0.071732

In [8]:
df.sub(row, axis=1)

one     three       two
a  1.535880       NaN  0.279883
b  0.000000  0.000000  0.000000
c  0.599907  1.379468  1.065003
d       NaN  1.316063  0.071732

In [9]:
df.sub(column, axis=0)

one     three  two
a  0.680728       NaN  0.0
b -0.575268 -1.101612  0.0
c -1.040365 -0.787147  0.0
d       NaN  0.142720  0.0

In [10]:
df2 = df
df2

one     three       two
a  0.577716       NaN -0.103012
b -0.958164 -1.484507 -0.382895
c -0.358257 -0.105039  0.682108
d       NaN -0.168444 -0.311164

In [11]:
df + df2
df.add(df2, fill_value=0)
df2

one     three       two
a  0.577716       NaN -0.103012
b -0.958164 -1.484507 -0.382895
c -0.358257 -0.105039  0.682108
d       NaN -0.168444 -0.311164

In [12]:
df.eq(df2)

one  three   two
a   True  False  True
b   True   True  True
c   True   True  True
d  False   True  True

In [13]:
df.ne(df2)

one  three    two
a  False   True  False
b  False  False  False
c  False  False  False
d   True  False  False

In [14]:
df>0

one  three    two
a   True  False  False
b  False  False  False
c  False  False   True
d  False  False  False

In [15]:
(df>0).all()


one      False
three    False
two      False
dtype: bool

In [16]:
df.empty

False

In [17]:
pd.DataFrame(columns=list('ABD')).empty

True

In [18]:
df+df == df*2

one  three   two
a   True  False  True
b   True   True  True
c   True   True  True
d  False   True  True

In [19]:
(df+df).equals(df*2)

True

In [20]:
df1 = pd.DataFrame({'col':['foo', 0, np.nan]})
df2 = pd.DataFrame({'col': ['foo', np.nan, 0]}, index=[0,2,1])
print df1
print df2

   col
0  foo
1    0
2  NaN
   col
0  foo
2  NaN
1    0


In [21]:
df1.equals(df2)

False

In [22]:
df1.equals(df2.sort_index())

True

In [23]:
df1 = pd.DataFrame({'A' : [1., np.nan, 3., 5., np.nan],
                    'B' : [np.nan, 2., 3., np.nan, 6.]})
df2 = pd.DataFrame({'A' : [5., 2., 4., np.nan, 3., 7.],
                    'B' : [np.nan, np.nan, 3., 4., 6., 8.]})

In [24]:
print df1
print df2
df1.combine_first(df2)

     A    B
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0
3  5.0  NaN
4  NaN  6.0
     A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0


A    B
0  1.0  NaN
1  2.0  2.0
2  3.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0

In [25]:
df

one     three       two
a  0.577716       NaN -0.103012
b -0.958164 -1.484507 -0.382895
c -0.358257 -0.105039  0.682108
d       NaN -0.168444 -0.311164

In [26]:
df.mean(0)

one     -0.246235
three   -0.585997
two     -0.028741
dtype: float64

In [27]:
df.mean(1)

a    0.237352
b   -0.941856
c    0.072937
d   -0.239804
dtype: float64

In [28]:
df.sum(0,skipna=False)

one           NaN
three         NaN
two     -0.114964
dtype: float64

In [29]:
print df.std()
ts_stand = (df - df.mean())/df.std()
print ts_stand

one      0.774043
three    0.778778
two      0.488539
dtype: float64
        one     three       two
a  1.064476       NaN -0.152028
b -0.919753 -1.153743 -0.724926
c -0.144723  0.617580  1.455051
d       NaN  0.536164 -0.578097


In [30]:
ts_stand.std()

one      1.0
three    1.0
two      1.0
dtype: float64

In [31]:
xs_stand = df.sub(df.mean(1), axis=0).div(df.std(1),axis=0)
print xs_stand

        one     three       two
a  0.707107       NaN -0.707107
b -0.029598 -0.984872  1.014471
c -0.794774 -0.328045  1.122818
d       NaN  0.707107 -0.707107


In [32]:
print xs_stand.std(1)

a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64


In [33]:
print df
df.cumsum()

        one     three       two
a  0.577716       NaN -0.103012
b -0.958164 -1.484507 -0.382895
c -0.358257 -0.105039  0.682108
d       NaN -0.168444 -0.311164


one     three       two
a  0.577716       NaN -0.103012
b -0.380448 -1.484507 -0.485908
c -0.738705 -1.589547  0.196200
d       NaN -1.757991 -0.114964

In [34]:
np.mean(df['one'])

-0.24623506580569318

In [35]:
np.mean(df['one'].values)

nan

In [36]:
frame = pd.DataFrame(np.random.randn(1000, 5), columns=['a', 'b', 'c', 'd', 'e'])
print frame

            a         b         c         d         e
0   -0.485911  0.296308  0.364474  0.298963 -0.313502
1   -1.853647 -1.083676 -0.521087 -0.835451 -0.809153
2   -0.719638  0.233920 -1.059725 -0.133826 -0.601983
3    0.945453 -0.603840 -0.510451  0.819184 -0.105370
4   -0.317644  0.513591 -1.072588  0.281225 -0.238236
5   -1.615334  0.338089  0.495207  0.709517  1.278396
6   -0.274450  2.332755  0.753673 -2.009803  0.570811
7    2.131892  1.105423 -1.035859 -0.918185 -0.507382
8    1.598870  0.501388 -1.072569 -1.851330  0.443952
9    0.810974  1.077197 -0.866217 -0.157655  1.057579
10   1.040736  0.192141 -2.036213  1.201515 -0.060761
11   0.658781 -0.196570  1.257876 -0.955992  0.174301
12   0.499312  1.266685 -1.241248  0.055114 -0.293116
13  -0.327811  0.495051  0.659717  1.547744 -1.726582
14   0.355664  1.246046  0.616459 -1.094179  1.224177
15   0.153724 -1.242967 -0.494591  0.725434  0.703441
16  -0.203017  0.937745  1.176213 -1.002390 -0.677946
17  -0.986275  0.417082 -0.2

In [37]:
frame.ix[::2]

a         b         c         d         e
0   -0.485911  0.296308  0.364474  0.298963 -0.313502
2   -0.719638  0.233920 -1.059725 -0.133826 -0.601983
4   -0.317644  0.513591 -1.072588  0.281225 -0.238236
6   -0.274450  2.332755  0.753673 -2.009803  0.570811
8    1.598870  0.501388 -1.072569 -1.851330  0.443952
10   1.040736  0.192141 -2.036213  1.201515 -0.060761
12   0.499312  1.266685 -1.241248  0.055114 -0.293116
14   0.355664  1.246046  0.616459 -1.094179  1.224177
16  -0.203017  0.937745  1.176213 -1.002390 -0.677946
18  -1.430301 -0.348723  0.443796  1.706298  1.592944
20  -0.393250  1.097041  1.077162 -0.199511  0.251831
22  -0.413857 -0.898553 -2.210917 -1.467530  0.890111
24  -0.658516 -0.129804  0.343106  1.740000  2.419670
26  -1.746391  1.035948 -0.595932 -1.283674  0.233364
28  -0.996674 -1.133378 -1.230087 -0.216951  0.300600
30   1.128698  1.602030 -1.018163 -2.107193 -0.083814
32   0.790773 -2.085629  0.697222  0.112826 -1.089289
34   0.118227 -1.538702 -1.211994  0.247911 -0.298539
36  -0.173523  1.996579  0.002578  0.644535 -0.514210
38   1.649907 -1.582651  0.431384  0.305880  0.802210
40  -0.707301  2.112051 -1.333802  0.672933  0.293184
42  -0.488491 -1.237407  1.118733  1.388623  0.379045
44  -0.397405  1.639132  1.189575 -0.800145 -0.138411
46   0.826696  0.771060  1.023852 -0.287955  0.912387
48   1.703388 -0.287519 -1.599308 -0.315359 -0.597822
50  -0.304704 -0.663664 -0.352073  0.970391  1.584237
52  -1.166120 -0.780222 -0.361176  0.516399 -0.706345
54   0.085205 -0.705041 -1.011847  1.557484  2.323059
56   0.054556  2.303626  0.633219  0.583612 -0.476984
58  -0.474798  0.187945  0.227878 -0.164927 -0.665986
..        ...       ...       ...       ...       ...
940  1.080558  0.188931 -0.711538 -0.498640 -0.818399
942  0.097228 -0.728227  0.439400 -0.368389  0.729791
944  0.562038  2.268906  1.872199  0.360067 -0.412306
946  0.331728  1.886694 -1.085320  0.170212  0.812106
948  0.477188  1.054023 -0.359696  0.626787  0.827730
950  0.012670  0.224304  1.737803 -0.405972 -1.397581
952  0.382935 -0.696278  0.834741 -1.458529  0.737635
954  1.460700  1.377762 -0.566145 -2.220585  1.328468
956 -1.566022 -1.412812  0.479851 -2.018116  1.031233
958  2.929393 -2.066755 -1.548640  0.219261  0.232976
960 -1.087084  0.739396  0.250211  0.231946 -0.118782
962  1.979273 -0.493727  1.031646 -2.232598 -0.713894
964  0.049523 -0.933426 -0.467421 -0.810087 -0.628192
966 -0.701676 -1.270186 -0.587757  2.949604 -0.992562
968  0.366182 -1.856865  0.111513 -0.813705 -0.802593
970  0.856803  2.052093 -1.957485  0.773280 -0.023535
972 -1.851608 -0.651980  0.114543 -0.279546 -1.659781
974  0.594113 -1.266044  0.914428 -0.051966 -0.923558
976  0.330202  1.270329 -0.190807 -0.816553  0.143781
978  1.392900 -1.340062  0.437641  1.158305  1.865921
980  0.177597 -1.208934  0.286461 -1.135924 -0.613996
982 -0.712701 -0.845475 -1.817984  1.731434 -1.235787
984 -0.888449 -0.105162 -0.301062  0.061917 -0.693589
986 -0.412910 -0.716914  1.869780 -0.608627  0.084801
988 -0.960939 -0.140023  0.252932 -0.659422  1.288284
990 -1.659442 -1.007350  0.447864  0.595908  1.423300
992 -0.208778 -0.371880 -0.591022 -0.954291  1.572130
994  0.936125 -0.086540  1.091334  0.694521 -0.290248
996  0.272442  0.241111 -0.348401 -2.006582 -2.541812
998  1.059748 -1.201869  0.914760 -0.297354  0.123690

[500 rows x 5 columns]

In [38]:
s1 = pd.Series(np.random.randn(5))
print s1

0   -1.403399
1   -0.523392
2   -0.564194
3   -1.448465
4   -0.712755
dtype: float64


In [39]:
s1.idxmin(), s1.idxmax()

(3, 1)

In [40]:
df1 = pd.DataFrame(np.random.randn(5, 3), columns=list('ABC'))

In [41]:
df1

A         B         C
0  1.047617 -1.266630  0.196679
1 -0.432576  0.400291 -0.450064
2  1.111101 -0.186179  0.639435
3 -0.348517  1.075023  0.145951
4 -0.362328  0.741484 -1.094782

In [42]:
df1.idxmin(axis=0)

A    1
B    0
C    4
dtype: int64

In [43]:
df1.idxmax(axis=1)

0    A
1    B
2    A
3    B
4    B
dtype: object

In [44]:
data = np.random.randint(0,7, size=50)
data

array([1, 6, 1, 6, 3, 1, 6, 3, 2, 2, 5, 2, 4, 3, 4, 4, 1, 0, 0, 1, 1, 5, 4,
       5, 4, 2, 5, 6, 1, 0, 6, 4, 1, 2, 3, 4, 3, 6, 6, 0, 4, 6, 0, 4, 3, 3,
       4, 5, 4, 4])

In [45]:
s = pd.Series(data)
print s

0     1
1     6
2     1
3     6
4     3
5     1
6     6
7     3
8     2
9     2
10    5
11    2
12    4
13    3
14    4
15    4
16    1
17    0
18    0
19    1
20    1
21    5
22    4
23    5
24    4
25    2
26    5
27    6
28    1
29    0
30    6
31    4
32    1
33    2
34    3
35    4
36    3
37    6
38    6
39    0
40    4
41    6
42    0
43    4
44    3
45    3
46    4
47    5
48    4
49    4
dtype: int32


In [46]:
s.value_counts()

4    12
6     8
1     8
3     7
5     5
2     5
0     5
dtype: int64

In [47]:
df

one     three       two
a  0.577716       NaN -0.103012
b -0.958164 -1.484507 -0.382895
c -0.358257 -0.105039  0.682108
d       NaN -0.168444 -0.311164

In [48]:
df.apply(np.mean)

one     -0.246235
three   -0.585997
two     -0.028741
dtype: float64

In [49]:
df.apply(np.mean, axis=1)

a    0.237352
b   -0.941856
c    0.072937
d   -0.239804
dtype: float64

In [50]:
df.apply(lambda x:x.max() - x.min())

one      1.535880
three    1.379468
two      1.065003
dtype: float64

In [51]:
df.apply(np.cumsum)

one     three       two
a  0.577716       NaN -0.103012
b -0.380448 -1.484507 -0.485908
c -0.738705 -1.589547  0.196200
d       NaN -1.757991 -0.114964

In [54]:
tsdf = pd.DataFrame(np.random.randn(1000, 3), columns=list('ABC'), 
                    index=pd.date_range('1/1/2000', periods=1000))
tsdf

A         B         C
2000-01-01 -1.913481  0.715990 -0.655609
2000-01-02  0.216844  0.265258  0.112409
2000-01-03  1.487179  0.642876 -0.389356
2000-01-04 -0.293519 -1.527745 -1.814227
2000-01-05  1.478865  0.354110 -1.422856
2000-01-06  0.633830 -1.937531  0.308995
2000-01-07 -1.728712  1.179697  1.141785
2000-01-08  0.475459  0.267539 -0.628681
2000-01-09 -1.338115  0.448127 -0.105140
2000-01-10  1.972683  1.149556  2.435331
2000-01-11 -1.243429  0.673061 -0.107976
2000-01-12  0.132649  0.487604  0.399501
2000-01-13  0.410841  1.289564 -0.872635
2000-01-14  0.276675 -0.012642 -1.966060
2000-01-15 -0.322628  0.286527 -0.869416
2000-01-16  0.004210  1.544064  1.179161
2000-01-17  0.605741 -0.439623  1.822367
2000-01-18 -1.291645  0.856846  0.686662
2000-01-19 -0.248882  0.672689  0.679824
2000-01-20  0.334251 -0.777615  1.229762
2000-01-21 -0.503280 -1.176333  1.090830
2000-01-22 -1.661229 -2.190703 -0.290638
2000-01-23 -0.247337 -0.164281  0.896781
2000-01-24 -2.214667 -1.546094  1.840164
2000-01-25 -0.153781  0.714453 -1.523802
2000-01-26 -1.362699 -0.586177  0.959875
2000-01-27 -0.278248 -0.123480  0.066145
2000-01-28  1.488718  1.145713 -0.032187
2000-01-29 -0.512630 -0.035212 -0.927779
2000-01-30  2.136808  0.984133 -2.719330
...              ...       ...       ...
2002-08-28  0.705771  0.391731 -0.908639
2002-08-29 -0.203038  0.539428 -0.246026
2002-08-30  0.668870  0.861511  0.129058
2002-08-31 -0.868345  0.726837  0.607707
2002-09-01  1.442048 -2.723047 -1.801504
2002-09-02 -0.395605 -0.760295  0.885788
2002-09-03  0.020136  0.833953 -0.960003
2002-09-04 -0.202290 -0.299152 -2.095714
2002-09-05 -0.183144  0.784763 -0.719783
2002-09-06  0.295314  0.163483 -0.435157
2002-09-07  0.568629 -0.483656 -1.344631
2002-09-08 -0.952746 -1.334189  0.041991
2002-09-09  0.071729  2.736541 -0.780913
2002-09-10  0.251536 -0.261050  0.102809
2002-09-11 -0.260607 -0.590570 -1.666910
2002-09-12  0.583793  1.040068  0.061788
2002-09-13  1.075656 -0.510035  0.016521
2002-09-14 -0.099780  2.761861  1.478063
2002-09-15  1.226383 -1.670101  1.222257
2002-09-16  1.543714 -0.765843 -0.584029
2002-09-17  1.080449  0.395607 -0.966395
2002-09-18  1.731626  0.545142  0.278215
2002-09-19  1.369867  1.907194 -1.068670
2002-09-20  0.163890 -0.391252 -0.240951
2002-09-21  1.826174  0.178923 -1.206591
2002-09-22  0.866565 -0.947990  1.090342
2002-09-23  0.159897  0.361642  0.262545
2002-09-24  1.101539 -0.380934  1.959826
2002-09-25 -0.520893 -0.061114 -1.486322
2002-09-26  1.478825 -0.442110  0.683418

[1000 rows x 3 columns]

In [56]:
tsdf.apply(lambda x:x.idxmax())

A   2001-08-09
B   2000-07-01
C   2000-09-07
dtype: datetime64[ns]

In [58]:
tsdf.apply(lambda x: x.idxmax(), axis=1)

2000-01-01    B
2000-01-02    B
2000-01-03    A
2000-01-04    A
2000-01-05    A
2000-01-06    A
2000-01-07    B
2000-01-08    A
2000-01-09    B
2000-01-10    C
2000-01-11    B
2000-01-12    B
2000-01-13    B
2000-01-14    A
2000-01-15    B
2000-01-16    B
2000-01-17    C
2000-01-18    B
2000-01-19    C
2000-01-20    C
2000-01-21    C
2000-01-22    C
2000-01-23    C
2000-01-24    C
2000-01-25    B
2000-01-26    C
2000-01-27    C
2000-01-28    A
2000-01-29    B
2000-01-30    A
             ..
2002-08-28    A
2002-08-29    B
2002-08-30    B
2002-08-31    B
2002-09-01    A
2002-09-02    C
2002-09-03    B
2002-09-04    A
2002-09-05    B
2002-09-06    A
2002-09-07    A
2002-09-08    C
2002-09-09    B
2002-09-10    A
2002-09-11    A
2002-09-12    B
2002-09-13    A
2002-09-14    B
2002-09-15    A
2002-09-16    A
2002-09-17    A
2002-09-18    A
2002-09-19    B
2002-09-20    A
2002-09-21    A
2002-09-22    C
2002-09-23    B
2002-09-24    C
2002-09-25    B
2002-09-26    A
Freq: D, dtype: object

In [60]:
df2

A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0

In [61]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s

a   -0.999001
b    0.832770
c    0.184280
d    1.012242
e   -0.244432
dtype: float64

In [62]:
s.reindex(['e', 'b', 'f', 'd'])

e   -0.244432
b    0.832770
f         NaN
d    1.012242
dtype: float64

In [63]:
df

one     three       two
a  0.577716       NaN -0.103012
b -0.958164 -1.484507 -0.382895
c -0.358257 -0.105039  0.682108
d       NaN -0.168444 -0.311164

In [64]:
s

a   -0.999001
b    0.832770
c    0.184280
d    1.012242
e   -0.244432
dtype: float64

In [65]:
s1 = s[:4]

In [66]:
s2 = s[1:]

In [67]:
s1.align(s2)

(a   -0.999001
 b    0.832770
 c    0.184280
 d    1.012242
 e         NaN
 dtype: float64, a         NaN
 b    0.832770
 c    0.184280
 d    1.012242
 e   -0.244432
 dtype: float64)

In [68]:
s1.align(s2, join='inner')

(b    0.832770
 c    0.184280
 d    1.012242
 dtype: float64, b    0.832770
 c    0.184280
 d    1.012242
 dtype: float64)

In [69]:
s1.align(s2, join='left')

(a   -0.999001
 b    0.832770
 c    0.184280
 d    1.012242
 dtype: float64, a         NaN
 b    0.832770
 c    0.184280
 d    1.012242
 dtype: float64)

In [70]:
df2

A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0

In [71]:
df

one     three       two
a  0.577716       NaN -0.103012
b -0.958164 -1.484507 -0.382895
c -0.358257 -0.105039  0.682108
d       NaN -0.168444 -0.311164

In [72]:
df.drop(['a', 'd'], axis=0)

one     three       two
b -0.958164 -1.484507 -0.382895
c -0.358257 -0.105039  0.682108

In [75]:
df.drop(['one'], axis=1)

three       two
a       NaN -0.103012
b -1.484507 -0.382895
c -0.105039  0.682108
d -0.168444 -0.311164

In [76]:
for col in df:
    print (col)

one
three
two
