In [2]:
import numpy as np
import pandas as pd

In [3]:
long_series = pd.Series(np.random.randn(1000))
print long_series.head()
print long_series.tail()

0    1.718906
1    0.503271
2    0.345008
3    0.147834
4   -0.492887
dtype: float64
995   -1.522735
996   -0.161742
997   -0.215290
998    0.474298
999   -0.261250
dtype: float64


In [4]:
index = pd.date_range('2000-01-01', periods=8)
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=['A', 'B', 'C'])
df.columns = [x.lower() for x in df.columns]
print df

                   a         b         c
2000-01-01 -1.203635 -0.123686  0.162814
2000-01-02 -0.250310  1.271096  0.020784
2000-01-03 -1.257550 -0.935831  1.414401
2000-01-04 -0.410831  0.109358 -0.048371
2000-01-05 -0.034875  0.284086 -0.156860
2000-01-06  0.376877 -1.528831 -0.330429
2000-01-07  1.137081 -0.525879 -0.428590
2000-01-08  0.655812 -0.598225 -0.643906


In [5]:
print df.values, type(df.values)

[[-1.20363534 -0.12368641  0.16281392]
 [-0.25030986  1.27109625  0.02078399]
 [-1.25754994 -0.9358306   1.41440136]
 [-0.41083057  0.10935782 -0.04837089]
 [-0.03487514  0.28408615 -0.15686021]
 [ 0.37687734 -1.5288308  -0.3304288 ]
 [ 1.13708072 -0.52587909 -0.42859027]
 [ 0.65581244 -0.59822549 -0.64390646]] <type 'numpy.ndarray'>


In [6]:
df = pd.DataFrame({'one' : pd.Series(np.random.randn(3), index=['a', 'b', 'c']),
                    'two' : pd.Series(np.random.randn(4), index=['a', 'b', 'c', 'd']),
                    'three' : pd.Series(np.random.randn(3), index=['b', 'c', 'd'])})
print df

        one     three       two
a  0.092958       NaN  1.695796
b -0.707688  0.848014  0.761491
c -1.271493  0.609862 -0.362506
d       NaN  0.663901 -0.376502


In [7]:
row = df.ix[1]
column = df['two']
print row
print column

one     -0.707688
three    0.848014
two      0.761491
Name: b, dtype: float64
a    1.695796
b    0.761491
c   -0.362506
d   -0.376502
Name: two, dtype: float64


In [8]:
df.sub(row, axis='columns')

one     three       two
a  0.800646       NaN  0.934305
b  0.000000  0.000000  0.000000
c -0.563805 -0.238152 -1.123996
d       NaN -0.184113 -1.137993

In [9]:
df.sub(row, axis=1)

one     three       two
a  0.800646       NaN  0.934305
b  0.000000  0.000000  0.000000
c -0.563805 -0.238152 -1.123996
d       NaN -0.184113 -1.137993

In [10]:
df.sub(column, axis=0)

one     three  two
a -1.602838       NaN  0.0
b -1.469179  0.086523  0.0
c -0.908988  0.972367  0.0
d       NaN  1.040402  0.0

In [11]:
df2 = df
df2

one     three       two
a  0.092958       NaN  1.695796
b -0.707688  0.848014  0.761491
c -1.271493  0.609862 -0.362506
d       NaN  0.663901 -0.376502

In [14]:
df + df2
df.add(df2, fill_value=0)
df2

one     three       two
a  0.092958       NaN  1.695796
b -0.707688  0.848014  0.761491
c -1.271493  0.609862 -0.362506
d       NaN  0.663901 -0.376502

In [15]:
df.eq(df2)

one  three   two
a   True  False  True
b   True   True  True
c   True   True  True
d  False   True  True

In [16]:
df.ne(df2)

one  three    two
a  False   True  False
b  False  False  False
c  False  False  False
d   True  False  False

In [17]:
df>0

one  three    two
a   True  False   True
b  False   True   True
c  False   True  False
d  False   True  False

In [24]:
(df>0).all()


one      False
three    False
two      False
dtype: bool

In [22]:
df.empty

False

In [23]:
pd.DataFrame(columns=list('ABD')).empty

True

In [25]:
df+df == df*2

one  three   two
a   True  False  True
b   True   True  True
c   True   True  True
d  False   True  True

In [26]:
(df+df).equals(df*2)

True

In [28]:
df1 = pd.DataFrame({'col':['foo', 0, np.nan]})
df2 = pd.DataFrame({'col': ['foo', np.nan, 0]}, index=[0,2,1])
print df1
print df2

   col
0  foo
1    0
2  NaN
   col
0  foo
2  NaN
1    0


In [31]:
df1.equals(df2)

False

In [32]:
df1.equals(df2.sort_index())

True

In [33]:
df1 = pd.DataFrame({'A' : [1., np.nan, 3., 5., np.nan],
                    'B' : [np.nan, 2., 3., np.nan, 6.]})
df2 = pd.DataFrame({'A' : [5., 2., 4., np.nan, 3., 7.],
                    'B' : [np.nan, np.nan, 3., 4., 6., 8.]})

In [34]:
print df1
print df2
df1.combine_first(df2)

     A    B
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0
3  5.0  NaN
4  NaN  6.0
     A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0


A    B
0  1.0  NaN
1  2.0  2.0
2  3.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0

In [35]:
df

one     three       two
a  0.092958       NaN  1.695796
b -0.707688  0.848014  0.761491
c -1.271493  0.609862 -0.362506
d       NaN  0.663901 -0.376502

In [36]:
df.mean(0)

one     -0.628741
three    0.707259
two      0.429570
dtype: float64

In [37]:
df.mean(1)

a    0.894377
b    0.300606
c   -0.341379
d    0.143699
dtype: float64

In [38]:
df.sum(0,skipna=False)

one           NaN
three         NaN
two      1.718279
dtype: float64

In [42]:
print df.std()
ts_stand = (df - df.mean())/df.std()
print ts_stand

one      0.685643
three    0.124856
two      0.998438
dtype: float64
        one     three       two
a  1.052587       NaN  1.268207
b -0.115143  1.127339  0.332440
c -0.937445 -0.780074 -0.793315
d       NaN -0.347265 -0.807333


In [43]:
ts_stand.std()

one      1.0
three    1.0
two      1.0
dtype: float64

In [46]:
xs_stand = df.sub(df.mean(1), axis=0).div(df.std(1),axis=0)
print xs_stand

        one     three       two
a -0.707107       NaN  0.707107
b -1.153286  0.626125  0.527161
c -0.988584  1.011038 -0.022455
d       NaN  0.707107 -0.707107


In [47]:
print xs_stand.std(1)

a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64


In [48]:
print df
df.cumsum()

        one     three       two
a  0.092958       NaN  1.695796
b -0.707688  0.848014  0.761491
c -1.271493  0.609862 -0.362506
d       NaN  0.663901 -0.376502


one     three       two
a  0.092958       NaN  1.695796
b -0.614730  0.848014  2.457287
c -1.886223  1.457875  2.094781
d       NaN  2.121776  1.718279

In [49]:
np.mean(df['one'])

-0.62874108782308447

In [50]:
np.mean(df['one'].values)

nan

In [51]:
frame = pd.DataFrame(np.random.randn(1000, 5), columns=['a', 'b', 'c', 'd', 'e'])
print frame

            a         b         c         d         e
0    0.401332  3.015809 -0.140535  1.611334 -0.386420
1    0.045028 -0.189404 -0.063752 -1.886387  0.216212
2   -0.300978  0.389917  0.077854 -0.849352  0.505837
3    1.883821  2.040372  0.413104  0.275154  0.315248
4    0.454804  0.822605  1.880371  0.356812  0.711691
5   -0.676484  1.007901  0.293606  1.478483 -0.888328
6    0.151768 -1.502526 -0.457642  0.901566 -0.666255
7   -1.954469 -0.357537 -0.162501 -0.580500 -0.393388
8   -0.553592  0.624339  3.430832  0.386662 -0.165615
9    0.742930  0.902720  0.404975  0.193827 -0.120025
10   0.394638 -1.523277 -0.057193 -0.855594  0.696145
11  -0.088447  0.462262 -0.495889  0.947680 -1.506870
12   0.175581 -0.205466 -1.797378 -0.027483  0.370841
13   1.206198 -1.381674  0.535634  0.030982 -0.521154
14  -2.049856 -0.396968  0.133944  1.234736  1.007981
15  -0.731993 -0.904714  0.206402 -1.260920 -0.103552
16   1.184405  0.590101 -0.170176 -0.308817 -1.299952
17  -0.250226  1.000023  0.6

In [52]:
frame.ix[::2]

a         b         c         d         e
0    0.401332  3.015809 -0.140535  1.611334 -0.386420
2   -0.300978  0.389917  0.077854 -0.849352  0.505837
4    0.454804  0.822605  1.880371  0.356812  0.711691
6    0.151768 -1.502526 -0.457642  0.901566 -0.666255
8   -0.553592  0.624339  3.430832  0.386662 -0.165615
10   0.394638 -1.523277 -0.057193 -0.855594  0.696145
12   0.175581 -0.205466 -1.797378 -0.027483  0.370841
14  -2.049856 -0.396968  0.133944  1.234736  1.007981
16   1.184405  0.590101 -0.170176 -0.308817 -1.299952
18  -1.970853  1.135044  0.775944 -0.385305 -0.366337
20  -1.433032  0.172755  1.112992 -0.494532  0.796101
22   0.588939 -1.126366 -0.139559  0.284000  0.764451
24   0.511605 -1.742163 -0.152068 -0.228735 -1.162031
26   0.492156 -0.049175  0.532656 -0.951030 -0.351522
28  -1.173714  1.613520  0.824039  0.378456  0.105424
30  -0.066372 -1.497736  0.354924  1.374580  0.144027
32   0.931490  1.093617  0.312383 -0.349243 -1.384009
34   0.282072  0.002546 -1.238936  1.750509  0.753019
36   1.724141  0.055033  0.345815 -0.079193  0.373376
38  -0.908442 -0.204992  0.129775 -0.308539  0.329901
40   0.292489  0.057059  1.424618 -1.427917  0.133062
42   1.965181  0.857414  0.515602  2.288327 -0.375747
44   2.075206 -0.365408 -0.754001 -0.716859 -0.643970
46  -0.153708 -0.176038 -0.103088  0.497766  0.724592
48  -1.085832 -1.205272 -2.071652 -1.025190 -0.611636
50  -1.330458 -1.053533  1.416178 -0.708034  0.934868
52   0.146003 -0.804264  0.667673  0.425577  0.044889
54  -0.056949 -1.233427  0.029189 -0.035619 -0.178616
56   0.465155  1.586668 -0.676664 -1.014627  1.276083
58  -1.532193  0.066304  1.692102 -0.243000  0.169418
..        ...       ...       ...       ...       ...
940  0.223703 -0.606171 -0.415372 -0.875170  1.020829
942 -1.593262  0.958192  1.071879  1.019012 -0.041986
944  2.773023 -0.080833  0.464203 -0.930154  0.409914
946 -0.999563 -2.337754  0.523096 -0.649703  0.692315
948  1.021543 -0.028880 -0.688957  0.170750  1.365135
950 -1.301999  0.031521  1.741696  1.031838 -1.538261
952  0.793979 -0.481639  1.233655 -1.485149  0.093764
954 -1.408719 -0.101314  0.822720 -0.790445  2.110730
956 -0.456508  0.556889  0.569152 -1.053575 -0.455045
958 -0.411044  0.290217 -0.415109  0.580002 -1.532492
960  0.418645  1.594136  0.534373  0.631201  0.555073
962  0.528167 -0.000881  0.869496 -0.661142  0.619683
964 -0.089274 -0.419808 -0.013921  1.613689 -0.304611
966  0.352191 -0.191876 -0.558646  0.481612  1.573890
968  0.934581  0.651262 -1.499455  0.114079 -0.712486
970  1.310308 -0.987443 -0.090994 -0.502263  0.371827
972  0.259717 -0.144009  1.215983 -1.134394  0.557677
974 -0.326341  0.409547  2.087909 -0.038339  1.655311
976  0.272496  1.031930 -0.074937 -0.415828 -0.968163
978 -1.867683  1.372144  1.032183  1.434206  0.912981
980 -2.355869  0.167208  0.353659  0.767239 -0.206178
982  2.187110 -0.155538 -0.253491 -0.471377 -0.087293
984 -0.356454 -0.245931 -0.428519 -0.380345 -0.392467
986  1.742435 -1.525140 -0.524192  0.171299 -0.263057
988 -0.589229  1.114357  1.069547  0.603893 -0.475563
990 -0.350332 -0.008534 -0.505290 -1.356035  0.281397
992  0.215826 -0.903762 -0.565306  1.533930 -0.819110
994  0.735353  1.387494  0.830351 -0.423807  0.692174
996 -0.350651 -0.291096 -0.268222  1.245154 -0.611692
998 -0.487397  1.045998  0.433444  2.080314 -0.962722

[500 rows x 5 columns]

In [53]:
s1 = pd.Series(np.random.randn(5))
print s1

0   -0.505091
1    0.418656
2   -1.086740
3   -1.703454
4   -0.510263
dtype: float64


In [54]:
s1.idxmin(), s1.idxmax()

(3, 1)

In [56]:
df1 = pd.DataFrame(np.random.randn(5, 3), columns=list('ABC'))

In [57]:
df1

A         B         C
0  0.038941  0.068466  0.065477
1  1.360119  0.461873  0.086755
2  0.344080 -0.403314  0.963892
3  0.404655 -0.658195 -1.742355
4  0.148110 -0.920364 -0.451697

In [58]:
df1.idxmin(axis=0)

A    0
B    4
C    3
dtype: int64

In [59]:
df1.idxmax(axis=1)

0    B
1    A
2    C
3    A
4    A
dtype: object